kind: Service
apiVersion: v1
metadata:
  name: musicmanagement-svc
  namespace: majesco-icd-dev
  labels:
    name: musicmanagement
spec:
  type: NodePort
  selector:
    app: musicmanagement
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30002
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: musicmanagement-deployment
  namespace: majesco-icd-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: musicmanagement
  template:
    metadata:
      labels:
        app: musicmanagement
    spec:
      containers:
      - name: musicmanagement
        image: musicmanagement-1.0.0:latest
        ports:
        - containerPort: 8080
        
        readinessProbe:
          httpGet:
            scheme: HTTP
            port: 8080
            path: /movies/
          initialDelaySeconds: 10
          periodSeconds: 30
          failureThreshold: 1		
          successThreshold: 1
          timeoutSeconds: 1
        
        livenessProbe:
          httpGet:
            scheme: HTTP
            path: /movies/
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 30
          failureThreshold: 1		
          successThreshold: 1
          timeoutSeconds: 1
        
        startupProbe:
          httpGet:
            scheme: HTTP
            path: /movies/
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 30
          failureThreshold: 1		
          successThreshold: 1
          timeoutSeconds: 1
        
        env:
         - name: JVM_ARGS
           value: -Xms1024m -Xmx4096m -XX:MaxPermSize=4096m
 